# Generated by Django 2.1 on 2020-03-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_blog', '0002_auto_20200315_2101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='legs',
            new_name='leg',
        ),
        migrations.DeleteModel(
            name='abs',
        ),
        migrations.DeleteModel(
            name='back',
        ),
        migrations.DeleteModel(
            name='bicep',
        ),
        migrations.DeleteModel(
            name='chest',
        ),
        migrations.DeleteModel(
            name='forearm',
        ),
        migrations.DeleteModel(
            name='fullbody',
        ),
        migrations.DeleteModel(
            name='shoulder',
        ),
        migrations.DeleteModel(
            name='tricep',
        ),
    ]
