# Generated by Django 2.1 on 2020-03-15 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_blog', '0004_chest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chest',
            new_name='chest1',
        ),
    ]
