# Generated by Django 3.0.4 on 2020-04-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_blog', '0011_abs1_forearm1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='content1',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content6',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='heading1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='heading2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='heading3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='heading4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='heading5',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='heading6',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image1',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image2',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image3',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image4',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image5',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image6',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
    ]
