# Generated by Django 3.0.4 on 2020-03-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
                ('thumbnail_desc', models.TextField(default='')),
                ('price', models.IntegerField()),
                ('full_desc', models.TextField(default='')),
                ('image1', models.ImageField(default='', upload_to='mart/images')),
                ('image2', models.ImageField(default='', upload_to='mart/images')),
                ('image3', models.ImageField(default='', upload_to='mart/images')),
                ('category', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('vendor_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='menshirt',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
                ('thumbnail_desc', models.TextField(default='')),
                ('price', models.IntegerField()),
                ('full_desc', models.TextField(default='')),
                ('image1', models.ImageField(default='', upload_to='mart/images')),
                ('image2', models.ImageField(default='', upload_to='mart/images')),
                ('image3', models.ImageField(default='', upload_to='mart/images')),
                ('category', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('vendor_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='mentrouser',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
                ('thumbnail_desc', models.TextField(default='')),
                ('price', models.IntegerField()),
                ('full_desc', models.TextField(default='')),
                ('image1', models.ImageField(default='', upload_to='mart/images')),
                ('image2', models.ImageField(default='', upload_to='mart/images')),
                ('image3', models.ImageField(default='', upload_to='mart/images')),
                ('category', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('vendor_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='newarrival',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
                ('thumbnail_desc', models.TextField(default='')),
                ('price', models.IntegerField()),
                ('full_desc', models.TextField(default='')),
                ('image1', models.ImageField(default='', upload_to='mart/images')),
                ('image2', models.ImageField(default='', upload_to='mart/images')),
                ('image3', models.ImageField(default='', upload_to='mart/images')),
                ('category', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('vendor_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='womenshirt',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
                ('thumbnail_desc', models.TextField(default='')),
                ('price', models.IntegerField()),
                ('full_desc', models.TextField(default='')),
                ('image1', models.ImageField(default='', upload_to='mart/images')),
                ('image2', models.ImageField(default='', upload_to='mart/images')),
                ('image3', models.ImageField(default='', upload_to='mart/images')),
                ('category', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('vendor_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='womentrouser',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
                ('thumbnail_desc', models.TextField(default='')),
                ('price', models.IntegerField()),
                ('full_desc', models.TextField(default='')),
                ('image1', models.ImageField(default='', upload_to='mart/images')),
                ('image2', models.ImageField(default='', upload_to='mart/images')),
                ('image3', models.ImageField(default='', upload_to='mart/images')),
                ('category', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('vendor_price', models.IntegerField()),
            ],
        ),
    ]
