# Generated by Django 3.0.4 on 2020-03-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0002_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('message', models.TextField(max_length=1000)),
                ('items', models.TextField(max_length=10000)),
                ('total_items', models.CharField(max_length=1000)),
            ],
        ),
    ]
